name: Build & Deploy to Azure Static Web App

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest

    env:
      VISION_ENDPOINT: ${{ secrets.VISION_ENDPOINT }}
      VISION_KEY: ${{ secrets.VISION_KEY }}
      OPENAI_ORG_ID: ${{ secrets.OPENAI_ORG_ID }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    name: Build and Deploy Job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"

          ###### Repository/Build Configurations ######
          app_location: "/" # App source code path relative to repository root
          ###### api_location: "" # Api source code path relative to repository root - optional
          output_location: "build" # Built app content directory, relative to app_location - optional
