name: Build & Deploy to Azure Static Web App

on:
  push:
    branches:
      - main

jobs:
  build_job:
    runs-on: ubuntu-latest

    name: Build Job

    outputs:
      build_folder: ${{ steps.build.outputs.build_folder }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: Install dependencies
        run: npm install

      - name: Build project
        id: build
        run: |
          npm run build
          echo "::set-output name=build_folder::$(pwd)/build"

      - name: List build directory contents
        run: ls -al $(pwd)/build

  deploy_job:
    needs: build_job
    runs-on: ubuntu-latest

    name: Deploy Job

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ needs.build_job.outputs.build_folder }}
          api_location: "" # api source code path
          output_location: ""
